version: '3'
services: 
    mysql:
        image: mysql:5.6
        environment: 
            - MYSQL_ROOT_PASSWORD=123456
            - MYSQL_USER=fullcycle
            - MYSQL_PASSWORD=123456
            - MYSQL_DATABASE=desafio02
        volumes: 
            - ./mysql/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    api:
        build: 
            context: node-api
        environment: 
            - DB_HOST=mysql
            - DB_DATABASE=desafio02
            - DB_USER=fullcycle
            - DB_PASSWORD=123456
        depends_on: 
            - mysql
    nginx:
        image: nginx:latest
        volumes: 
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports: 
            - 8080:80
        depends_on: 
            - api